/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    IAntDesignGithubFilled: typeof import('~icons/ant-design/github-filled')['default']
    IRiFacebookBoxFill: typeof import('~icons/ri/facebook-box-fill')['default']
    IRiLinkedinBoxFill: typeof import('~icons/ri/linkedin-box-fill')['default']
    IRiYoutubeFill: typeof import('~icons/ri/youtube-fill')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
